### ISSUE TITLE
Create Layout with grid

### ISSUE THREAD

**Issue by GrandSchtroumpf** [blockframes/blockframes#2579]
# Layout
Mathilde uses a grid system for organizing the layout.
Let's implement something similar to simplify the implementation.

A grid divide the layout (page without sidenav) into [columns / gutters / margin](https://material.io/design/layout/responsive-layout-grid.html#columns-gutters-and-margins). And the width of each element should be based on those columns / gutters. 

## Breakpoints
The size of gutters / margin & amount of columns changes depending on the breakpoints. A good starting point is the one defined by the [material documentation](https://material.io/design/layout/responsive-layout-grid.html#Breakpoints).

## Mixins
First step would be to create mixins : 
```scss
$layout: var(--layout); // this is a dynamic variable from the layout component
$column: calc(0.2 * $layout); // 20% of the layout
$gutter: 24px;
@mixin col($amount) {
  width: calc($amount * $column - ($amount - 1) * $gutter);
}
```
We need to define the --layout variable on the layout component because the grid doesn't apply on sidebar.
A quick example on how to perform that in dashboard: 
```html
<mat-sidenav-content [ngClass]="{ full: sidenav?.opened && sidenav?.mode === 'side' }"
```
```scss
mat-sidenav-content.full {
  --layout: 100vw;
}
mat-sidenav-content:not(.full) {
  --layout: calc(100vw - 300px); // 300px here would be the size of the sidenav
}
```

## Directive
The goal here is to wrap the `FlexLayout` directives into a simpler system : 
```html
<section fxGrid>
  <mat-card [fxCol]="2" [fxCol.sm]="4"></mat-card>
</section>
```
