### ISSUE TITLE
Responsive Large Screens - Landing page

### ISSUE THREAD

**Issue by RemcoSimonides** [blockframes/blockframes#6239]
We start with implementing this responsive capability in the landing page. More pages will follow later.

[Zeplin](https://app.zeplin.io/project/5f3100d317a0041be2ad99c4/screen/60dc4213015aef929f65789f)

Link to discussion in design issue: #5560

**Comment by GrandSchtroumpf** [comment]
The best way to achieve that is to have a global `--max-width` css variable that we can call from anywhere, and create a global class `max-width` (or some better name).
There are two options: 
- use padding
- use margin

# Padding
```scss
.max-width {
  padding-left: minmax(24px, calc((100vh - var(--max-width)) / 2));
  padding-right: minmax(24px, calc((100vh - var(--max-width)) / 2));
  box-sizing: border-box;
}
```
_I put 24px a minimum padding as a reference. Please check with @stephanie-cascade8 for the real value._

This has the advantage of not needing much update on the html : 
```html
<header class="max-width">

</header>
<section class="max-width">

</section>
```

# Margin
```scss
.max-width {
  max-width: var(--max-width);
  margin: auto;
}
```
The css is easier to understand but it means that now we need to wrap the content with a section and apply the background on the section: 
```html
<header>
  <article class="max-width">
  ...
  </article>
</header>
<section>
  <article class="max-width">
  ...
  </article>
</section>
```
